export const QUEUE_ADD_PENDING_JOB = 'QUEUE_ADD_PENDING_JOB'
export const QUEUE_ADD_PENDING_JOB_SUCCESS = 'QUEUE_ADD_PENDING_JOB_SUCCESS'
export const QUEUE_ADD_PENDING_JOB_FAIL = 'QUEUE_ADD_PENDING_JOB_FAIL'

export const QUEUE_REMOVE_PENDING_JOB = 'QUEUE_REMOVE_PENDING_JOB'
export const QUEUE_REMOVE_PENDING_JOB_SUCCESS = 'QUEUE_REMOVE_PENDING_JOB_SUCCESS'
export const QUEUE_REMOVE_PENDING_JOB_FAIL = 'QUEUE_REMOVE_PENDING_JOB_FAIL'

export const QUEUE_ADD_WORKING_JOB = 'QUEUE_ADD_WORKING_JOB'
export const QUEUE_ADD_WORKING_JOB_SUCCESS = 'QUEUE_ADD_WORKING_JOB_SUCCESS'
export const QUEUE_ADD_WORKING_JOB_FAIL = 'QUEUE_ADD_WORKING_JOB_FAIL'

export const QUEUE_ADD_COMPLETED_JOB = 'QUEUE_ADD_COMPLETED_JOB'
