// Pending types
export const ADD_PENDING_ITEM = 'ADD_PENDING_ITEM'
export const ADD_PENDING_ITEM_SUCCESS = 'ADD_PENDING_ITEM_SUCCESS'
export const ADD_PENDING_ITEM_FAIL = 'ADD_PENDING_ITEM_FAIL'

export const REMOVE_PENDING_ITEM = 'REMOVE_PENDING_ITEM'
export const REMOVE_PENDING_ITEM_SUCCESS = 'REMOVE_PENDING_ITEM_SUCCESS'
export const REMOVE_PENDING_ITEM_FAIL = 'REMOVE_PENDING_ITEM_FAIL'

export const ADD_PENDING_ITEM_TO_WORKING = 'ADD_PENDING_ITEM_TO_WORKING'

// Size types
export const INCREMENT_SIZE = 'INCREMENT_SIZE'
export const DECREMENT_SIZE = 'DECREMENT_SIZE'

// Completed Size types
export const INCREMENT_COMPLETED_SIZE = 'INCREMENT_COMPLETED_SIZE'
export const DECREMENT_COMPLETED_SIZE = 'DECREMENT_COMPLETED_SIZE'

// Empty types
export const UNSET_EMPTY = 'UNSET_EMPTY'
export const SET_EMPTY = 'SET_EMPTY'

// Working Item types
export const ADD_WORKING_ITEM = 'ADD_WORKING_ITEM'
export const ADD_WORKING_ITEM_SUCCESS = 'ADD_WORKING_ITEM_SUCCESS'
export const ADD_WORKING_ITEM_FAIL = 'ADD_WORKING_ITEM_FAIL'
export const CLEAR_WORKING_ITEM = 'CLEAR_WORKING_ITEM'

// Completed types
export const ADD_COMPLETED_ITEM = 'ADD_COMPLETED_ITEM'
export const ADD_COMPLETED_ITEM_SUCCESS = 'ADD_COMPLETED_ITEM_SUCCESS'
export const ADD_COMPLETED_ITEM_FAIL = 'ADD_COMPLETED_ITEM_FAIL'

export const REMOVE_WORKING_ITEM = 'REMOVE_WORKING_ITEM'
export const REMOVE_WORKING_ITEM_SUCCESS = 'REMOVE_WORKING_ITEM_SUCCESS'
export const REMOVE_WORKING_ITEM_FAIL = 'REMOVE_WORKING_ITEM_FAIL'

export const UPDATE_WORKING_ITEM = 'UPDATE_WORKING_ITEM'
