// Pending types
export const ADD_PENDING_ITEM = 'ADD_PENDING_ITEM'
export const ADD_PENDING_ITEM_SUCCESS = 'ADD_PENDING_ITEM_SUCCESS'
export const ADD_PENDING_ITEM_FAIL = 'ADD_PENDING_ITEM_FAIL'

export const REMOVE_PENDING_ITEM = 'REMOVE_PENDING_ITEM'
export const REMOVE_PENDING_ITEM_SUCCESS = 'REMOVE_PENDING_ITEM_SUCCESS'
export const REMOVE_PENDING_ITEM_FAIL = 'REMOVE_PENDING_ITEM_FAIL'

export const ADD_PENDING_ITEM_TO_WORKING = 'ADD_PENDING_ITEM_TO_WORKING'

// Working Item types
export const ADD_WORKING_ITEM = 'ADD_WORKING_ITEM'
export const ADD_WORKING_ITEM_SUCCESS = 'ADD_WORKING_ITEM_SUCCESS'
export const ADD_WORKING_ITEM_FAIL = 'ADD_WORKING_ITEM_FAIL'
export const CLEAR_WORKING_ITEM = 'CLEAR_WORKING_ITEM'
export const UPDATE_WORKING_ITEM = 'UPDATE_WORKING_ITEM'

// Completed types
export const ADD_COMPLETED_ITEM = 'ADD_COMPLETED_ITEM'
export const ADD_COMPLETED_ITEM_SUCCESS = 'ADD_COMPLETED_ITEM_SUCCESS'
export const ADD_COMPLETED_ITEM_FAIL = 'ADD_COMPLETED_ITEM_FAIL'

export const REMOVE_WORKING_ITEM = 'REMOVE_WORKING_ITEM'
export const REMOVE_WORKING_ITEM_SUCCESS = 'REMOVE_WORKING_ITEM_SUCCESS'
export const REMOVE_WORKING_ITEM_FAIL = 'REMOVE_WORKING_ITEM_FAIL'
